### PR TITLE
Added Leaflet demonstrator

### PR DESCRIPTION
**Pull request by afrazer-os**
Added a Leaflet demonstrator, using the mapbox-gl-leaflet plugin to load our VTS as a layer: https://github.com/mapbox/mapbox-gl-leaflet

### CODE REVIEW

**Comment by mattlovett** [comment]
Rather than check in the leaflet-mapbox-gl code, how about using the CDN?
<script src="https://unpkg.com/mapbox-gl-leaflet/leaflet-mapbox-gl.js"></script>

Matt

**Comment by afrazer-os** [comment]
> Rather than check in the leaflet-mapbox-gl code, how about using the CDN?
> 
> <script src="https://unpkg.com/mapbox-gl-leaflet/leaflet-mapbox-gl.js"></script>
> Matt

Good spot - the example I was copying referenced a local file. The CDN is a much better option! :)

**Comment by mattlovett** [comment]
Hi Alex.

It's basically good, but something odd happens if you keep zooming in. It seems like the zoom gets stuck at a certain level, and extra zooms in animate the map but end up as they were. Once you've done that you need extra zoom out clicks before you start to back up. Had you noticed that?

Matt

**Comment by afrazer-os** [comment]
I did notice the odd zooming in animation, but didn't realise it impacted the zoom out. I've switched the "maxZoom" from the vector layer to the map itself, and it seems to have done the trick.

**Pull request merged**
